version: '3'

services:
  pgvector:
    image: ankane/pgvector
    environment:
      - POSTGRES_PASSWORD=!ChangeMe!
      - POSTGRES_USER=myuser
    ports:
      - 5432:5432

  redis:
    image: redis/redis-stack:latest
    ports:
      - 6379:6379
      - 8001:8001
